### PR TITLE
current solution to retrieve custom_data vector variable length. core…

### PR DESCRIPTION
**Pull request by elmbeech**
…/PhysiCell_cell.cpp had to be modified that it works for empty vectors.  the problem was reported to the PhysiCell core developer team.

### CODE REVIEW

**Comment by elmbeech** [comment]
hi @fyffep , 

This is another pull request. A solution to retrieve the vector variable (antigenSequence, antibodySequence) length. 
Works as well with empty vectors, but for this moment I had to comment out a line in core/PhysiCell_cell.cpp that the code does not break. This is not ideal. I informed Paul to get his input on what we might have to do differently.
For the moment, this solution lets us at least further develop on the project.

**Comment by elmbeech** [comment]
second commit: code can now extract the sequence length from Vector_Variables too, and has a way to loop over all elements and print them.

**Comment by elmbeech** [comment]
by the way, Paul said we should for the moment go with the commented out core/PhysiCell_cell.cpp version.

**Comment by fyffep** [comment]
Resolve conflicts with your other PR first. (That one was just merged in)

**Comment by elmbeech** [comment]
sorry @fyffep, I resolved the conflict, but pressed a button too much. 
now it is already merged.

**Comment by fyffep** [comment]
Okay, no problem

**Comment by elmbeech** [comment]
in any case, I tested the code by running it, and it works all fine.

**Pull request merged**
